### PR TITLE
character sprites

### PR DESCRIPTION
**Pull request by StarryDraco**
12 32x32 cels of  character animations. There are 4 idle sprites and 8 walking sprites. The sprites may not entirely line up in a way that's good for animation though.

character

### CODE REVIEW

**Review by MichaPika — APPROVED** [review]
Looks good to me! Love the character!

**Review by laylabmanley — CHANGES_REQUESTED** [review]
Looks awesome, but where does the right arm come into play?

Also, could you update the sprite sheets to where there is either no gap or only a 1px gap between frames?

**Comment by StarryDraco** [comment]
The right arm is going to be for the flashlight. As for the sprite sheet, the image I used for the screenshot isn't entirely indicative of how its formatted, I opted to use individual png files for each frame instead of a sprite sheet since it was easier to format those. I could reformat the frames as a sprite sheet if that works better.

**Review by laylabmanley — APPROVED** [review]
All good then! :smile:

**Pull request merged**
